[profile.default]
# src = "src" #switch to this and everything compiles
src = "src/contracts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
